apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.service.appName }}
spec:
  type: {{ .Values.service.type }}
  ports:
{{- range .Values.service.ports }}
    - name: "{{ .name }}"
      port: {{ .port }}
      targetPort: {{ .targetPort }}
{{- end }}
  selector:
    app: {{ .Values.service.appName }}