apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.http.name }}
  namespace: {{ .Values.namespace }}
  annotations:
{{- with .Values.ingress.http.annotations }}
  {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  ingressClassName: {{ .Values.ingress.http.className }} # сначала - minikube addons enable ingress
  rules:
  # вызывать с указанием порта 80 после запуска туннеля minikube tunnel
{{- range .Values.ingress.http.rules }}
  - host: {{ .host }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: {{ .pathType | default "Prefix" }}
        backend:
          service:
            name: {{ .backend.service.name }}
            port:
              number: {{ .backend.service.port }}
      {{- end }}
{{- end }}