# Logger config
logger:
  level: "INFO"
# GRPC server config
grpcServer:
  port: ${GRPC_SERVER_PORT}
# HTTP server config
httpServer:
  host: ${HTTP_SERVER_HOST}
  port: ${HTTP_SERVER_PORT}
  readTimeout: "5s"
# Database config
database:
  driver: "pgx"
  uri: ${DB_URI}
# Storage type
storage: "SQL" # SQL / MEMORY
# Timezone
timezone: "Europe/Moscow"