# Logger config
logger:
  level: "DEBUG"
# Database config
database:
  driver: "pgx"
  uri: ${DB_URI}
# Queue producer config
queue:
  uri: ${QUEUE_URI}
  exchangeName: "calendar-events"
  exchangeType: "direct" # direct|fanout|topic|x-custom
  queueName: "notifications-queue"
  routingKey: "notifications"
# Schedule config
schedule:
  notifyCron: "*/5 * * * * *"
  clearCron: "*/10 * * * * *"
  notifyPeriod: "1m" # период для уведомления в будущем
  notifyScanPeriod: "1h" # период для проверки событий без уведомлений в прошлом
  clearPeriod: "8760h"
# Timezone
timezone: "Europe/Moscow"