# Logger config
logger:
  level: "INFO"
# Database config
database:
  driver: "pgx"
  uri: ${DB_URI}
# Queue consumer config
queue:
  uri: ${QUEUE_URI}
  exchangeName: "calendar-events"
  exchangeType: "direct" # direct|fanout|topic|x-custom
  queueName: "notifications-queue"
  routingKey: "notifications"
  consumerTag: "sender-consumer"
# Timezone
timezone: "Europe/Moscow"