# Logger config
logger:
  level: "INFO"
# Queue consumer config
queue:
  uri: "amqp://rmuser:rmpassword@127.0.0.1:5672/"
  exchangeName: "calendar-events"
  exchangeType: "direct" # direct|fanout|topic|x-custom
  queueName: "notifications-queue"
  routingKey: "notifications"
  consumerTag: "sender-consumer"